Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ----- Figure 2: "There is a vibrant culture at UNI" by Respondent Type -----


agree_vibrant = round(100 * df['QID23'].isin(["Strongly agree","Somewhat agree"]).mean(),2)
_ = glue("agree_vibrant", agree_vibrant, display=False)  # prevents display

qid23_order = [
    "Strongly agree",
    "Somewhat agree", 
    "Neither agree nor disagree",
    "Somewhat disagree",
    "Strongly disagree",
]
df_c2 = (
    df.assign(
        QID4=df["QID4"].map(fill_unaffiliated),
        QID23=pd.Categorical(df["QID23"], categories=qid23_order, ordered=True)
    )
    .rename(columns={"QID4": "Respondent Type"})
)

pct_makes_sense = round(100*len(df['QID23'].isin(["Strongly agree",
    "Somewhat agree", 
    "Neither agree nor disagree"]).mean(),2)
_ = glue("pct_makes_sense", pct_makes_sense, display=False)  # prevents display

c2_df = (
    df_c2.groupby(["QID23", "Respondent Type"], observed=True, dropna=False)
         .size()
         .reset_index(name="Count")
)
c2_df["Percent"] = c2_df["Count"] / len(df)

fig2 = px.bar(
    c2_df, x="QID23", y="Percent",
    color="Respondent Type",
    barmode="stack",
    title='"The university has a vibrant open source culture"'
)
fig2.update_layout(
    yaxis=dict(tickformat=".1%"),
    xaxis_title="",
    plot_bgcolor="white",
    paper_bgcolor="white"
)
fig2.write_html('_static/fig2.html', full_html=False, include_plotlyjs='cdn')
------------------


[0;36m  Cell [0;32mIn[3], line 22[0;36m[0m
[0;31m    pct_makes_sense = round(100*len(df['QID23'].isin(["Strongly agree",[0m
[0m                           ^[0m
[0;31mSyntaxError[0m[0;31m:[0m '(' was never closed


